- name: installing python
  ansible.builtin.command: dnf install python3 gcc python3-devel -y

- name: app setup
  include_role:
    name: common
    tasks_from: app-setup
    
- name: python setup
  include_role:
    name: common
    tasks_from: python

- name: systemd_service
  include_role:
    name: common
    tasks_from: systemd